### ISSUE TITLE
Expand API documentation for countries endpoint

### ISSUE THREAD

**Issue by aedanmc** [aedanmc/travelo-hey#135]
The documentation for the `/country` API endpoint does not currently explain what each of the fields in the output data are. Explanations for the following fields would be helpful for implementing the countries page, particularly in regards to the use case about sorting and searching for countries:
- Rank
- lgbtqSafetyIndex
- safetyScore

The rest are pretty straightforward and do not need any further detail in my opinion.

**Comment by mik3ycodez** [comment]
See PR #139
