### ISSUE TITLE
GCP project has exceeded its credit balance

### ISSUE THREAD

**Issue by C-Christensen** [aedanmc/travelo-hey#150]
The status to the connection to the Google API is "REQUEST DENIED", error message says"You must enable Billing on the Google Cloud Project". I am not sure if we ran out of credits or if the issue is being caused by something else.

**Comment by C-Christensen** [comment]
Update: It looks like our project was converted to a Firebase project and the billing information deleted because it was downgraded to a Spark $0/month plan. It was then upgraded to a Blaze pay as you go plan but there are no billing details. It looks like we need to move to someone’s account.

**Comment by mik3ycodez** [comment]
Update: We were able to update the linked billing to @C-Christensen but API responses are still coming back `REQUEST DENIED`. This may be due to a time delay for GCP to rollover the changes in the billing. But we will continue to investigate.

**Comment by mik3ycodez** [comment]
GCP Billing updated and resolved. API is calling resources correctly.
