### ISSUE TITLE
Routing Rendering Bug

### ISSUE THREAD

**Issue by matthewdbroom13** [aedanmc/travelo-hey#151]
The browser you are using (including the version): 
Chrome 101.0.4951.54
The operating system you are using (Windows, OS X, Linux, etc): 
OS X
The location/webpage where you discovered the bug: 
Search Page when clicking on individual business card
The behavior you expected to see: 
Business's page would render on the screen showing information about the business
The behavior you actually saw: 
Page would briefly render (without all information) before reloading back to the search page. The URL changes, but the page content does not update. 
A sequence of steps taken to reproduce the bug, if you can: 
1) start the server/client 
2) attempt to click on business

**Comment by aedanmc** [comment]
Things that have been tried (unsuccessful):
1. Setting up nested routes with parent route as "/"
2. Using URL search params without React Router
3. Forcing a reload using `window.location.reload` to get the correct page content
