### ISSUE TITLE
Location Cards Rendering Cutoff

### ISSUE THREAD

**Issue by aki18-1861529** [aedanmc/travelo-hey#153]
The browser you are using (including the version): 
Chrome (Version 101.0.4951.54)

The operating system you are using (Windows, OS X, Linux, etc): 
Windows

The location/webpage where you discovered the bug: 
Landing page

The behavior you expected to see: 
Location cards showing the name and maybe some brief details of each location.

The behavior you actually saw: 
Location cards are rendering the photo placeholder with some of the text cutoff by the card parameters. It seems that the card is still clickable by the cutoff text that is hidden too. Below is an image of the how the landing page was rendered:
![image](https://user-images.githubusercontent.com/43832000/170165873-6a70701d-e987-4312-9a20-744df02c07e7.png)

A sequence of steps taken to reproduce the bug, if you can:
1. Cloned the repository using `git clone https://github.com/aedanmc/travelo-hey.git`.
2. Used `npm run all` to build and test all systems.
3. Loaded locaclhost:3000 to view landing page.

**Comment by aedanmc** [comment]
@C-Christensen @mik3ycodez Are you two interested in taking this on as current maintainers of the search page? It might be a pretty simple bug to fix since it seems like a styling issue more than anything.

**Comment by mik3ycodez** [comment]
> @C-Christensen @mik3ycodez Are you two interested in taking this on as current maintainers of the search page? It might be a pretty simple bug to fix since it seems like a styling issue more than anything.

This is already a work in progress. Styling has been updated with the PR #146 . We have some other plans for further modifying the styling.

**Comment by mik3ycodez** [comment]
![Screen Shot 2022-05-24 at 9 07 12 PM](https://user-images.githubusercontent.com/27905079/170177688-208d9bb8-e5e4-4ed6-9de0-268047f628f4.png)
