### ISSUE TITLE
Software architecture

### ISSUE THREAD

**Issue by aedanmc** [aedanmc/travelo-hey#16]
Provide an overview of your system. Specifically:

- Identify and describe the major software components and their functionality at a conceptual level.

- Specify the interfaces between components.

- Describe in detail what data your system stores, and how. If it uses a database, give the high level database schema. If not, describe how you are storing the data and its organization.

- If there are particular assumptions underpinning your chosen architecture, identify and describe them.

- For each of two decisions pertaining to your software architecture, identify and briefly describe an alternative. For each of the two alternatives, discuss its pros and cons compared to your choice.

Brought over from https://homes.cs.washington.edu/~rjust/courses/CSE403/project/04_design.html for Travelo-Hey! progress tracking.

**Comment by mik3ycodez** [comment]
I think this is complete. Please reopen if needed.
