### ISSUE TITLE
Update/ Clean up Single Country API endpoint

### ISSUE THREAD

**Issue by aedanmc** [aedanmc/travelo-hey#167]
Currently the `/country` endpoint has a few things that I am not sure are up to date or not:
1. There is a parameter called `form_addr` that does not seem to be related to the `/country` endpoint. Is this necessary?
2. Does the `/country` endpoint still use URL params, or does it now use JSON body objects as its parameters?
3. Is it currently possible to use the `/countries` endpoint's data to query the `/country` endpoint? If not, would it be possible to implement this for the purpose of having the countries page work using this strategy?
4. This is more of a nitpick and not as much of a priority, but what was the motivation behind formatting the endpoint to have a slash right next to a question mark? `/country/?name=USA` feels redundant.

**Comment by mik3ycodez** [comment]
We believe we have a fix for this, however, we are confirming with @matthewdbroom13 if `/country` endpoint is being used in the business pages. Will update when we hear back.

**Comment by aedanmc** [comment]
Sounds good! Thank you for the update 🙌

**Comment by mik3ycodez** [comment]
Resolution is in place and API documentation is up-to-date. Please refer to the documentation when using the endpoints.
