### ISSUE TITLE
Design Equality Rating Look

### ISSUE THREAD

**Issue by mik3ycodez** [aedanmc/travelo-hey#46]
What goes into our rating system? 

- Scale
- Shape
- Color
- Metrics

**Comment by aedanmc** [comment]
I'm a bit confused about what the decision to make here is. Are we saying that we should choose from one of these to have as part of our rating system?

**Comment by mik3ycodez** [comment]
The decision is for how we should display it to the user. Do we want yellow stars? Pink unicorns? Rainbows? /shrug For the scale and metric, we pretty much have that done. Each question has a point value and we just need to work out the proper formula for normalizing to a [0,1] or [0,5] type scale.

**Comment by aedanmc** [comment]
I think yellow stars is probably good enough; no need to reinvent the wheel here. As for scale, a [0, 5] would be good! I think the more familiar we can make it the better so there learning involved in what a rating means is minimized.

**Comment by mik3ycodez** [comment]
Let's include this as an agenda item for our 4.26 Tuesday meeting.
